### PR TITLE
Modella 1.0.0

### PR DESCRIPTION
**Pull request by matthewmueller**
# Modella 1.0.0

Modella 1.0.0 is on the horizon. It's not working yet, but it's getting really close. 1.0.0 was rewritten from the ground up to offer support for some of the latest browser and server-side features. As a result, Modella 1.0.0 will be a **breaking change**. Modella has a more refined API. Most plugins will need to be updated (or pinned).

Some of the features coming:
## getter/setter support

Old:

``` js
User.attr('name').attr('age')

user.name('matt')
user.age(25)
```

New:

``` js
User.attr('name').attr('age')

user.name = 'matt';
user.age = 25;
```

This applies to some other operations as well:

Old:

``` js
user.toJSON()
user.primary(2)
```

New:

``` js
user.json
user.primary = 2;
```
## Optional generator support in environments that support it

Old:

``` js
user.save(function () { ... });
```

New:

``` js
yield user.save();
// or...
user.save(function () { ... });
```
## Multiple syncs

Before modella 1.0.0, you couldn't have multiple sync layers on the same model. Now it's easier than ever to add multiple sync layers

Old:

``` js
model.create = fn;
```

New:

``` js
model.sync.create = function a() {};
model.sync.create = function b() {};
```
## Remove .save()

**Under consideration:** We all love `.save()`, but it makes way too many assumptions about how you're going to save and which events it should fire. Replace with `.create()` and `.update()`
## Hooks

In addition to events, you will now be able to hook into, `before` and `after` events on all CRUD operations. These hooks can be synchronous, asynchronous or generator functions.You can also define your own hooks using `Model.hook(...)` & `Model.trigger(...)`.
## More

Here's a stream of consciousness on how the API looks:

``` js
// server & browser
var user = User(attrs)

// STATIC:

// setting attributes
User.attr(name, opts)

// computing attributes
User.computed(name, str|fn)

// PROTOTYPE:

user.changed()

// set an object
user.attr[name] = value

// get or set the primary
user.primary

// return json
user.json

// has the model been
// synced from a remote
user.synced

// COMMON:

// use a plugin
// used to set up events, hooks and syncs
// optionally pass an environment variable
User.use([env], fn);

// events
// don't modify or halt execution flow
// may or may not modify state
// unordered, run asynchronously
User.on(event, fn);
User.emit(event, [args, ...])

// hooks
// may halt execution flow
// will probably modify state
// ordered, run sequentially
User.hook(event, fn|gen);
User.trigger(event, [args, ...], [done])

// SYNC:

// predefined events
creating
created
updating
updated
removing
removed
finding
found
saving
saved

// setters & getters
User.create // batch
user.create // single
User.update // batch
user.update // single
User.remove // batch
user.remove // single
User.all    // find many
User.find   // find one

// signatures

  // static:
  User.find(query, [opts], [fn])
  User.sync.find = function(query, opts, fn) {}

  User.all(query, [opts], [fn])
  User.sync.all = function(query, opts, fn) {}

  User.create(users, [opts], [fn])
  User.update(users, [opts], [fn])
  User.remove(users, [opts], [fn])

  // proto:
  user.create([opts], [fn])
  User.sync.create = function(opts, fn) {}
  user.update([opts], [fn])
  User.sync.update = function(opts, fn) {}
  user.remove([opts], [fn])
  User.sync.remove = function(opts, fn) {}
```

---

Let me know if you have any questions or thoughts!

### CODE REVIEW

**Comment by focusaurus** [comment]
-1 on getters/setters (in this case and broadly)

**Comment by dweinstein** [comment]
- :-1: on getters/setters
- :+1: keeping toJSON()

**Comment by aukan** [comment]
Looks nice. I'm looking forward for the `user.changed()` method. When are you guys planning to release?

I have another question about `User.find(query ...`  Will this still support `User.find(id..`, or that will be depreciated?

+1 to keep toJSON()

**Comment by lvivier** [comment]
@matthewmueller are you still working on 1.0? Need a hand?

**Comment by matthewmueller** [comment]
@lvivier hey man, sorry for the delay on this. I wanted to rethink this idea a little bit. 

I tend to agree with the sentiment outlined here: http://seldo.com/weblog/2011/08/11/orm_is_an_antipattern. 

So I'd like the next iteration of modella to address some of the concerns outlined here. Or perhaps create a spinoff of modella entirely. 

I think one of the pieces of the puzzle (validation and transformation) has been implemented: https://github.com/lapwinglabs/rube

**Comment by matthewmueller** [comment]
_(Going through old PRs and closing them)_

**Pull request closed without merging**
